title: 'Learn2 with Git Sync'
default_lang: en
author:
  name: 'Alf Gaida'
  email: agaida@siduction.org
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'Learn2 with Git Sync'
summary:
  size: 300
